[Feature] Rename to studio-sdk
chili-publish/studio-sdk pull request #275
Opened 2023-05-09 13:33 UTC by brapoprod

This PR renames the project to studio-sdk coming from editor-sdk

## Related tickets

-   [WRS-1176](https://support.chili-publish.com/projects/WRS/issues/WRS-1176)

2023-05-09 13:33 UTC, pkgacek approved these changes

2023-05-09 14:09 UTC, srares76 submitted a review, later dismissed

2023-05-09 19:04 UTC, pkgacek approved these changes

2023-05-10 07:30 UTC, abdelhalimkhouas submitted a review, later dismissed

2023-05-10 07:33 UTC, alexandraFlavia9 requested changes

2023-05-10 07:33 UTC, alexandraFlavia9 commented on COMMUNICATION_GUIDELINES.md
> +Our [CODE OF CONDUCT](https://github.com/chili-publis/studio-sdk/blob/main/CODE_OF_CONDUCT.md) outlines the behavior we expect from our community. Maintainers are responsible for enforcing violations
chili-publish

2023-05-10 07:40 UTC, brapoprod commented on README.md
> +This project is [MIT licensed](https://github.com/chili-publis/studio-sdk/blob/develop/LICENSE)
this was there for a veeeery long time
good catch

2023-05-10 07:44 UTC, pkgacek approved these changes

2023-05-10 07:49 UTC, alexandraFlavia9 approved these changes

2023-05-10 07:53 UTC, merged