[EDT-1167] - connector mapping to variable ids
chili-publish/studio-sdk pull request #368
Opened 2023-10-10 13:55 UTC by olegsolodukhin

This PR

## Related tickets

-   [EDT-1167](https://chilipublishintranet.atlassian.net/browse/EDT-1167) in scope of this ticket only the method comments and test values were changed

## Screenshots

2023-10-10 14:02 UTC, Dvergar requested changes

2023-10-10 14:02 UTC, Dvergar commented on packages/sdk/src/controllers/ConnectorController.ts
> +     * for variables is should follow the format "var.[variable id]". e.g. var.6B29FC40-CA47-1067-B31D-00DD010662DA
```suggestion
     * For variables it should follow the format "var.[variable id]". e.g. var.6B29FC40-CA47-1067-B31D-00DD010662DA
```

If you add an example for variables, you should probably add one for strings.

2023-10-10 14:23 UTC, Dvergar commented on packages/sdk/src/controllers/ConnectorController.ts
> +     * for variables is should follow the format "var.[variable id]". e.g. var.6B29FC40-CA47-1067-B31D-00DD010662DA
Maybe also add that a `name` is being mapped to a `value` (this is the actual model) and that your _"var..."_ is the `value`.

2023-10-11 06:48 UTC, Matthiee submitted a review, later dismissed

2023-10-11 09:18 UTC, Dvergar approved these changes

2023-10-12 12:12 UTC, abdelhalimkhouas approved these changes

2023-10-13 12:14 UTC, merged