[NO-TICKET] [Genie] Processed testing feedback
chili-publish/studio-sdk pull request #369
Opened 2023-10-10 14:41 UTC by pietervp

Add Training data

2023-10-10 14:47 UTC, pietervp commented
![90ff163b-5226-4a46-a9ca-f6e549bbddd5](https://github.com/chili-publish/studio-sdk/assets/956362/6afa663c-03ad-48e1-8013-17621e74a02f)

This PR prevents Genie from being too chatty when asked to write a function

2023-10-10 15:37 UTC, brapoprod submitted a review, later dismissed

2023-10-10 15:40 UTC, brapoprod commented
![image](https://github.com/chili-publish/studio-sdk/assets/54845569/affa6a79-c498-4a66-8f43-19ee47c8e24d)

2023-10-11 06:46 UTC, Matthiee requested changes

2023-10-11 06:46 UTC, Matthiee commented on packages/actions/training.json
> +        "response": "function moveFramesToRandomLocation(){ \n  // Get all frames\n  const allFrames = studio.frames.all();\n\n  // Move each frame to a random position\n  allFrames.forEach(frame =>
The response is not valid, the function is missing a closing bracket. 

```suggestion
        "response": "function moveFramesToRandomLocation(){ \n  // Get all frames\n  const allFrames = studio.frames.all();\n\n  // Move each frame to a random position\n  allFrames.forEach(frame => {\n    const randomX = Math.random() * getPageWidth();\n    const randomY = Math.random() * getPageHeight();\n    frame.move(randomX, randomY);\n  });\n}\nmoveFramesToRandomLocation();"
```

2023-10-11 08:41 UTC, Matthiee approved these changes

2023-10-11 13:44 UTC, brapoprod approved these changes

2023-10-11 13:44 UTC, merged