[Feature][EDT-1172] Remove unnecessary connector methods
chili-publish/studio-sdk pull request #373
Opened 2023-10-13 11:27 UTC by evan-mcgeek

This PR removes all unused methods from connectors and introduces 2 different capabilities for media and font

## Related tickets

-   [EDT-1172](https://chilipublishintranet.atlassian.net/browse/EDT-1172)

2023-10-13 11:38 UTC, Dvergar requested changes
`FontConnector.d.ts` & `MediaConnector.d.ts` should also be updated.

2023-10-13 11:38 UTC, Dvergar commented on packages/sdk/src/types/ConnectorTypes.ts
> +    query?: boolean;
I know they were nullable before you PR but I don't see why 🤔.

2023-10-13 13:17 UTC, Dvergar requested changes
LGTM but still those `FontConnector.d.ts`, `MediaConnector.d.ts` & `Connector.Shared.d.ts` to update with the new split capabilities model.

2023-10-13 14:23 UTC, Dvergar requested changes
Wondering if your prettyfier is not a bit too agressive 😅

2023-10-13 14:23 UTC, Dvergar commented on types/Connector.Shared.d.ts
> +export type FontConnectorCapabilities = {
I'd but that one in `FontConnector.d.ts`.

2023-10-13 14:23 UTC, Dvergar commented on types/Connector.Shared.d.ts
> +export type MediaConnectorCapabilities = {
And that one in `MediaConnector.d.ts`.

2023-10-13 15:11 UTC, evan-mcgeek commented
![image](https://github.com/chili-publish/studio-sdk/assets/74073782/0bbe01c0-e63b-4a91-9b0c-8065613cd899)

2023-10-13 15:50 UTC, Dvergar submitted a review, later dismissed

2023-10-16 07:49 UTC, pietervp commented on packages/sdk/src/types/ConnectorTypes.ts
> +    detail: boolean;
filtering is still a capability

2023-10-16 07:50 UTC, pietervp commented on packages/sdk/src/types/ConnectorTypes.ts
> +    query: boolean;
same here, filtering should be kept, it is a part of the query function. It will allow us to show a search bar for a connector or not.

2023-10-16 07:51 UTC, pietervp commented on types/FontConnector.d.ts
> +    preview: boolean;
Same here, re-add filtering

2023-10-17 11:18 UTC, Dvergar approved these changes

2023-10-17 11:59 UTC, pietervp approved these changes

2023-10-17 12:03 UTC, merged