[Feature] Add onTokenExpired listener
chili-publish/studio-sdk pull request #396
Opened 2023-11-30 16:22 UTC by Dvergar

This PR is a SPIKE!

Allows for blocking https requests on engine-side until a new token is returned by the `onTokenExpired` listener.

## Related tickets

[EDT-1231](https://chilipublishintranet.atlassian.net/browse/EDT-1231)

2023-12-01 07:51 UTC, NicolaVerbeeck requested changes

2023-12-01 07:51 UTC, NicolaVerbeeck commented on packages/sdk/src/controllers/SubscriberController.ts
> +    onTokenExpired = () => {
If we expect this method to be used for more than just grafx tokens we should:

- Add connector id to body
- Rename this method to 'onAuthExpired' to be more in line with other auth types

2023-12-01 07:51 UTC, NicolaVerbeeck commented on packages/sdk/src/controllers/SubscriberController.ts
> +    onTokenExpired = () => {
Not sure about the naming though :)

2023-12-05 07:11 UTC, Matthiee submitted a review, later dismissed

2023-12-05 08:39 UTC, alexandraFlavia9 submitted a review, later dismissed

2023-12-20 16:49 UTC, psamusev approved these changes

2023-12-21 09:12 UTC, brapoprod approved these changes

2024-01-04 08:54 UTC, merged