[EDT-1311] Add methods to set the background color for a layout
chili-publish/studio-sdk pull request #413
Opened 2024-01-24 20:41 UTC by NicolaVerbeeck

This PR

## PR Guidelines

- [X] I have read the [contribution and PR guidelines](/chili-publish/studio-sdk/blob/main/CONTRIBUTING.md)

## Related tickets

-   [EDT-1311](https://chilipublishintranet.atlassian.net/browse/EDT-1311)
-   [WRS-1564](https://chilipublishintranet.atlassian.net/browse/WRS-1564)

## Screenshots

2024-01-30 10:43 UTC, brapoprod submitted a review, later dismissed

2024-02-01 15:38 UTC, Matthiee submitted a review, later dismissed

2024-02-01 22:07 UTC, Dvergar approved these changes

2024-02-22 09:14 UTC, Dvergar requested changes

2024-02-22 09:14 UTC, Dvergar commented on packages/sdk/src/controllers/LayoutController.ts
> +    setLayoutFillColor = async (id: Id, color: ColorUsage) => {
```suggestion
    setFillColor = async (id: Id, color: ColorUsage) => {
```

2024-02-22 09:14 UTC, Dvergar commented on packages/sdk/src/controllers/LayoutController.ts
> +    resetLayoutFillColor = async (id: Id) => {
```suggestion
    resetFillColor = async (id: Id) => {
```

2024-02-22 10:30 UTC, srares76 approved these changes

2024-02-22 10:30 UTC, Matthiee approved these changes

2024-02-22 10:31 UTC, brapoprod approved these changes

2024-02-22 10:33 UTC, Dvergar approved these changes

2024-02-22 10:33 UTC, merged