[Feature] [EDT-1211] Add page bleed
chili-publish/studio-sdk pull request #419
Opened 2024-02-08 07:05 UTC by Matthiee

This PR adds page bleed models and methods.

## PR Guidelines

- [X] I have read the [contribution and PR guidelines](/chili-publish/studio-sdk/blob/main/CONTRIBUTING.md)

## Related tickets

-   [EDT-1211](https://chilipublishintranet.atlassian.net/browse/EDT-1211)

2024-02-08 07:56 UTC, NicolaVerbeeck commented on packages/sdk/src/controllers/LayoutController.ts
> +     * otherwise will set all positions to the same value.
Should we add a comment that this implies (or does not) areBleedValuesCombined change

2024-02-08 09:21 UTC, Dvergar requested changes

2024-02-08 09:21 UTC, Dvergar commented on packages/sdk/src/types/LayoutTypes.ts
Looks like `onSelectedLayoutPropertiesChanged` is returning a `LayoutPropertiesType` which is `SelectedLayoutProperties` on engine-side and that you updated.

It lacks `bleed` in scope of this ticket, `fillColor` in scope of your PR and `animate`, `intent` & `unit` in scope of our past PRs. 🥲

2024-02-08 11:14 UTC, Matthiee commented on packages/sdk/src/types/LayoutTypes.ts
https://chilipublishintranet.atlassian.net/browse/EDT-1351

2024-02-08 11:17 UTC, Dvergar approved these changes

2024-02-20 12:34 UTC, srares76 approved these changes

2024-02-21 14:03 UTC, merged