[EDT-1386] Add methods to create barcode and set basic settings
chili-publish/studio-sdk pull request #429
Opened 2024-03-06 15:55 UTC by NicolaVerbeeck

This PR

## PR Guidelines

- [x] I have read the [contribution and PR guidelines](/chili-publish/studio-sdk/blob/main/CONTRIBUTING.md)

## Related tickets

-   [EDT-1386](https://chilipublishintranet.atlassian.net/browse/EDT-1386)

## Screenshots

2024-03-07 06:25 UTC, Matthiee requested changes

2024-03-07 06:25 UTC, Matthiee commented on packages/sdk/src/controllers/FrameController.ts
> +    createBarcodeFrame = async (type: BarcodeType, x?: number, y?: number, width?: number, height?: number) => {
Given that all these properties are optional I would suggest the following:

```suggestion
    createBarcodeFrame = async (type: BarcodeType, position?: { x?: number, y?: number, width?: number, height?: number }) => {
```

2024-03-07 06:25 UTC, Matthiee commented on packages/sdk/src/types/BarcodeTypes.ts
> +export enum BarcodeType {
These probably need to be exported in `index.ts`?

2024-03-20 17:37 UTC, Dvergar commented
Just a side-thought, since `Barcode` has its own controller maybe it would be great to explode frame creation and frame specific helpers into their own controllers as well for `Shape` and `Text` frames for consistency's sake (that would be easily retro-compatible as well).

2024-03-21 07:34 UTC, NicolaVerbeeck commented on packages/sdk/src/controllers/FrameController.ts
> +            .addBarcodeFrame(type, position?.x, position?.y, position?.width, position?.height)
In the implementation for addFrame on engine side we allready have to do an exhaustive search to see if we are actually adding a 'regular' frame or a 'shape' frame. This locks the implementation down to a clearer naming scheme

2024-03-21 07:35 UTC, NicolaVerbeeck commented
> Just a side-thought for a future refactoring: since `Barcode` has its own controller maybe it would be great to explode frame creation and frame specific helpers into their own controllers as well for `Shape` and `Text` frames for consistency's sake (that would be easily retro-compatible as well).

We discussed this with @brapoprod but decided to move this to v2 instead to keep things consistent

2024-03-21 12:44 UTC, Dvergar requested changes

2024-03-21 12:44 UTC, Dvergar commented on packages/sdk/src/controllers/LayoutController.ts
> +     * @param enabled  whether the fill color should be enabled or disabled
```suggestion
     * @param enabled whether the fill color should be enabled or disabled
```
🔎

2024-03-21 12:44 UTC, Dvergar commented on packages/sdk/src/controllers/BarcodeController.ts
> +        var allowToggleText = true;
```suggestion
        let allowToggleText = true;
```

2024-03-22 13:25 UTC, Dvergar submitted a review, later dismissed

2024-04-02 12:20 UTC, psamusev approved these changes

2024-04-02 13:53 UTC, srares76 submitted a review, later dismissed

2024-04-02 13:53 UTC, brapoprod approved these changes

2024-04-02 14:09 UTC, Matthiee approved these changes

2024-04-02 14:09 UTC, srares76 approved these changes

2024-04-03 05:40 UTC, Matthiee commented on .github/CODEOWNERS
> +/packages/sdk/ @Matthiee @Dvergar @NicolaVerbeeck @olegsolodukhin @evan-mcgeek @brapoprod
```suggestion
/packages/sdk/ @chili-publish/flutter
```

2024-04-03 08:13 UTC, Dvergar submitted a review, later dismissed

2024-04-10 07:36 UTC, srares76 approved these changes

2024-04-10 07:38 UTC, brapoprod approved these changes

2024-04-10 07:38 UTC, merged