[Feature] Allow barcode frame sources to receive null as a source
chili-publish/studio-sdk pull request #447
Opened 2024-04-15 10:31 UTC by srares76

This PR allows barcode frame sources to receive null as a source.

## PR Guidelines

- [ ] I have read the [contribution and PR guidelines](/chili-publish/studio-sdk/blob/main/CONTRIBUTING.md)

## Related tickets

-   [WRS-1644](https://support.chili-publish.com/projects/WRS/issues/WRS-1644)

## Screenshots

2024-04-15 10:32 UTC, NicolaVerbeeck approved these changes

2024-04-15 10:33 UTC, NicolaVerbeeck requested changes

2024-04-15 10:35 UTC, NicolaVerbeeck commented on packages/sdk/src/controllers/BarcodeController.ts
> +    setBarcodeSource = async (id: Id, source: BarcodeSource | null) => {
@Matthiee  @brapoprod  your call

2024-04-15 10:50 UTC, Matthiee commented on packages/sdk/src/controllers/BarcodeController.ts
> +    setBarcodeSource = async (id: Id, source: BarcodeSource | null) => {
Consider creating a `removeBarcodeSource` method that calls the engine with `null` argument.

2024-04-15 12:25 UTC, srares76 commented on packages/sdk/src/controllers/BarcodeController.ts
> +    setBarcodeSource = async (id: Id, source: BarcodeSource | null) => {
Done

2024-04-15 12:39 UTC, Matthiee submitted a review, later dismissed

2024-04-15 14:53 UTC, abdelhalimkhouas approved these changes

2024-04-16 08:16 UTC, NicolaVerbeeck approved these changes
LGTM

2024-04-16 08:17 UTC, evan-mcgeek approved these changes
did you read [contribution and PR guidelines](https://github.com/chili-publish/studio-sdk/blob/main/CONTRIBUTING.md) ? :)

2024-04-16 08:17 UTC, merged