[Feature] [EDT-1472] Add options to control start/stop/end characters
chili-publish/studio-sdk pull request #449
Opened 2024-04-22 10:59 UTC by NicolaVerbeeck

This PR

## PR Guidelines

- [X] I have read the [contribution and PR guidelines](/chili-publish/studio-sdk/blob/main/CONTRIBUTING.md)

## Related tickets

-   [EDT-1472](https://chilipublishintranet.atlassian.net/browse/EDT-1472)

## Screenshots

2024-04-22 13:45 UTC, Dvergar reviewed
We're sending `drawStartStopChars` to engine but it seems that we do not support it yet? I saw that the `dart_barcode` lib merged the related PR but what about engine?

2024-04-22 13:58 UTC, NicolaVerbeeck commented
Engine is ready but waiting for release on the dart barcode lib before creating PR

2024-04-23 15:02 UTC, brapoprod commented on packages/sdk/src/controllers/BarcodeController.ts
> +                allowToggleDrawStartAndEndChar = true;
```suggestion
                allowToggleDrawStartAndStopChar = true;
```

2024-04-23 15:21 UTC, brapoprod requested changes
Jeroen asks to align the SDK methods with the copy that is used:
allowLightMarginToggle
allowStartStopCharactersToggle

Also the setters should be renamed accordingly

2024-04-23 20:58 UTC, NicolaVerbeeck commented
> Jeroen asks to align the SDK methods with the copy that is used: allowLightMarginToggle allowStartStopCharactersToggle
> 
> Also the setters should be renamed accordingly

That means that for every terminology for every barcode type we need to add more booleans :/

2024-04-23 20:58 UTC, closed without merging