[EDT-1476] Add methods related to number variables
chili-publish/studio-sdk pull request #456
Opened 2024-05-03 20:20 UTC by NicolaVerbeeck

This PR

## PR Guidelines

- [X] I have read the [contribution and PR guidelines](/chili-publish/studio-sdk/blob/main/CONTRIBUTING.md)

## Related tickets

-   [EDT-1476](https://chilipublishintranet.atlassian.net/browse/EDT-1476)

## Screenshots

2024-05-06 05:16 UTC, Matthiee requested changes

2024-05-06 05:16 UTC, Matthiee commented on packages/sdk/src/controllers/VariableController.ts
> +            .updateNumberVariableProperties(id, JSON.stringify(update))
Add a private method that takes in the delta model

2024-05-06 05:16 UTC, Matthiee commented on packages/sdk/src/controllers/VariableController.ts
> +        const update = { min: minimum };
Make the delta update model strongly typed

2024-05-06 05:16 UTC, Matthiee commented on packages/sdk/src/controllers/VariableController.ts
> +    setDecimalSeparator = async (id: string, decimalSeparator: string) => {
@chili-publish/react thoughts about the following?

```suggestion
    setDecimalSeparator = async (id: string, decimalSeparator: '' | '.' | ',' | ' ') => {
```

2024-05-06 05:16 UTC, Matthiee commented on packages/sdk/src/controllers/VariableController.ts
> +     * @param numberOfDecimals the number of decimals to use
Add the allowed values here

2024-05-06 05:16 UTC, Matthiee commented on packages/sdk/src/controllers/VariableController.ts
> +    setNumberOfDecimals = async (id: string, numberOfDecimals: number) => {
Consider making this a `1 | 2 | ...` instead of plain number

2024-05-06 05:16 UTC, Matthiee commented on packages/sdk/src/controllers/VariableController.ts
> +     * @param stepSize the step size or null to remove the step size
Add that the number needs to be positive

2024-05-06 13:36 UTC, Dvergar requested changes
We should probably prefix the number exclusive properties with _number_ (or alike) in the name such as:

`setNumberStepSize`
`setNumberShowStepper`
...

2024-05-27 14:15 UTC, psamusev submitted a review, later dismissed

2024-05-27 18:31 UTC, abdelhalimkhouas approved these changes

2024-05-28 06:40 UTC, psamusev approved these changes

2024-05-28 06:43 UTC, Matthiee approved these changes

2024-05-29 07:25 UTC, merged