[Feature][EDT-1757] Fit mode alignment
chili-publish/studio-sdk pull request #542
Opened 2024-12-09 13:28 UTC by NicolaVerbeeck

This PR builds on top of the manual crop work to introduce alignment modes for image fits

## PR Guidelines

- [X] I have read the [contribution and PR guidelines](/chili-publish/studio-sdk/blob/main/CONTRIBUTING.md)

## Related tickets

-   [EDT-1757](https://chilipublishintranet.atlassian.net/browse/EDT-1757)

## Screenshots

2024-12-11 13:12 UTC, Dvergar approved these changes

2024-12-13 11:15 UTC, abdelhalimkhouas approved these changes

2024-12-31 10:20 UTC, brapoprod requested changes

2024-12-31 10:20 UTC, brapoprod commented on packages/sdk/src/controllers/FrameController.ts
> +    setImageFrameFitModeAlignment = async (imageFrameId: Id, alignment: FitModeAlignment) => {
why diverge from product naming. setImageFrameFitModePosition

2025-01-06 08:32 UTC, NicolaVerbeeck commented on packages/sdk/src/controllers/FrameController.ts
> +    setImageFrameFitModeAlignment = async (imageFrameId: Id, alignment: FitModeAlignment) => {
Since in indesign it is called alignment, I suspect the naming in the UI will be updated at some point to reflect this

2025-01-06 10:49 UTC, brapoprod commented on packages/sdk/src/controllers/FrameController.ts
> +    setImageFrameFitModeAlignment = async (imageFrameId: Id, alignment: FitModeAlignment) => {
In other tools it's called position as well as CSS, as integrator I'm also more fan of calling it position. PO also confirmed that it was their opinion to call it position. I didn't know about InDesign, let's validate again

2025-01-16 07:06 UTC, merged